# Note: this Dockerfile uses trackC, which uses trackB in its pre-build stage
# The goal here is to have a three level dependency chain

# ---- Stage 1: Build ----
FROM track-c-build:prebake AS track-e-build
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
RUN rm track-c-build.txt
RUN touch track-e-build.txt

# ---- Stage 2: Test ----
FROM track-e-build AS track-e-test
RUN python -m unittest discover -s tests || echo "Tests failed, but continuing"
RUN touch track-e-test.txt

# ---- Stage 3: Final Runtime ----
FROM fedora:43 AS track-e-final
WORKDIR /app
RUN touch track-e-final.txt
COPY --from=track-e-build /app /app
CMD ["python", "helloBase.py"]