# ---- Stage 1 pre-build ----
FROM base:prebake AS track-b-pre-build
RUN dnf install -y python3 python3-pip; dnf clean all
RUN touch track-b-pre-build.txt

# ---- Stage 2: Build ----
FROM track-b-pre-build:prebake AS track-b-build
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
RUN touch track-b-build.txt

# ---- Stage 3: Test ----
FROM track-b-build AS track-b-test
RUN python -m unittest discover -s tests || echo "Tests failed, but continuing"
RUN touch track-b-test.txt

# ---- Stage 4: Final Runtime ----
FROM fedora:43 AS track-b-final
WORKDIR /app
COPY --from=track-b-build /app /app
RUN touch track-b-final.txt
CMD ["python", "helloBase.py"]