# ---- Stage 1: pre-build ----
FROM base:prebake AS track-d-pre-build
RUN dnf install -y python3 python3-pip
RUN touch track-d-pre-build.txt

# ---- Stage 2: Build ----
FROM track-d-pre-build AS track-d-build
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
RUN touch track-d-build.txt

# ---- Stage 3: Test ----
FROM track-d-build AS track-d-test
RUN python -m unittest discover -s tests || echo "Tests failed, but continuing"
RUN touch track-d-test.txt

# ---- Stage 4: Final Runtime ----
FROM fedora:43 AS track-d-final
WORKDIR /app
RUN touch track-d-final.txt
COPY --from=track-d-build /app /app
CMD ["python", "helloBase.py"]