# ---- Stage 1: pre-build ----
FROM track-b-pre-build:prebake AS track-c-pre-build
RUN dnf install -y python3 python3-pip
RUN touch track-c-pre-build.txt

# ---- Stage 2: Build ----
FROM track-c-pre-build AS track-c-build
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
RUN touch track-c-build.txt

# ---- Stage 3: Test ----
FROM track-c-build AS track-c-test
RUN python -m unittest discover -s tests || echo "Tests failed, but continuing"
RUN touch track-c-test.txt

# ---- Stage 4: Final Runtime ----
FROM fedora:43 AS track-c-final
WORKDIR /app
RUN touch track-c-final.txt
COPY --from=track-c-build /app /app
CMD ["python", "helloBase.py"]